apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpbinproxy
spec:
  virtualhost:
    fqdn: local.projectcontour.io
    tls:
      secretName: contour-local-tls
  routes:
  - services:
    - name: httpbin
      port: 80