apiVersion: v1
kind: Namespace
metadata:
  name: projectcontour-deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  namespace: projectcontour-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: echo
          image: stevesloka/echo-server
          command: ["echo-server"]
          args:
            - --echotext=This is the BLUE site!
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue
  name: blue
  namespace: projectcontour-deploy
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: blue
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  namespace: projectcontour-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green
  
  template:
    metadata:
      labels:
        app: green
    
    spec:
      containers:
        - name: echo
          image: stevesloka/echo-server
          command: ["echo-server"]
          args:
            - --echotext=This is the GREEN site!
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: green

  name: green
  namespace: projectcontour-deploy
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: green

  type: ClusterIP


---
apiVersion: v1
kind: Namespace
metadata:
  name: projectcontour-deploy2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  namespace: projectcontour-deploy2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: echo
          image: stevesloka/echo-server
          command: ["echo-server"]
          args:
            - --echotext=This is the BLUE site2!
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue
  name: blue
  namespace: projectcontour-deploy2
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: blue
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  namespace: projectcontour-deploy2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green
  
  template:
    metadata:
      labels:
        app: green
    
    spec:
      containers:
        - name: echo
          image: stevesloka/echo-server
          command: ["echo-server"]
          args:
            - --echotext=This is the GREEN site2!
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: green

  name: green
  namespace: projectcontour-deploy2
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: green

  type: ClusterIP
