apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: projectcontour-roots2
  #namespace: projectcontour-roots
spec:
  virtualhost:
    fqdn: local.projectcontour.io
  includes:
    - name: blue
    #- name: blue2
      #namespace: projectcontour-deploy2
      namespace: projectcontour-deploy
      conditions:
        - prefix: /deploy

    - name: canary2
      namespace: projectcontour-deploy2
      #namespace: projectcontour-deploy
      conditions:
        - prefix: /deploy/canary

  routes:
    - services:
        - name: rootapp2
        #- name: rootapp
          port: 80
      conditions:
        - prefix: /
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: blue
  namespace: projectcontour-deploy
spec:
  routes:
    - services:
        - name: blue
          port: 80
          
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: green
  namespace: projectcontour-deploy
spec:
  routes:
    - services:
        - name: green
          port: 80

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: canary
  namespace: projectcontour-deploy
spec:
  routes:
    - services:
        - name: blue
          port: 80
          weight: 40

        - name: green
          port: 80
          weight: 60          









---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: blue2
  namespace: projectcontour-deploy2
spec:
  routes:
    - services:
        - name: blue2
          port: 80
          
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: green2
  namespace: projectcontour-deploy2
spec:
  routes:
    - services:
        - name: green2
          port: 80

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: canary2
  namespace: projectcontour-deploy2
spec:
  routes:
    - services:
        - name: blue2
          port: 80
          weight: 0

        - name: green2
          port: 80
          weight: 100                    