apiVersion: v1
kind: Namespace
metadata:
  name: projectcontour-roots
---

apiVersion: v1
kind: Namespace
metadata:
  name: projectcontour-deploy
---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: projectcontour-roots
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/projectsesame/kuard-amd64:1
        name: kuard
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: projectcontour-roots
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  namespace: projectcontour-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green
  
  template:
    metadata:
      labels:
        app: green
    
    spec:
      containers:
        - name: echo
          image: stevesloka/echo-server
          command: ["echo-server"]
          args:
            - --echotext=This is the GREEN site in projectcontour-deploy!
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: green

  name: green
  namespace: projectcontour-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: green
  sessionAffinity: None
  type: ClusterIP