apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: projectcontour-roots
spec:
  virtualhost:
    fqdn: local.projectcontour.io
  routes:
  - services:
    - name: kuard
      port: 80
    loadBalancerPolicy:
      strategy: Cookie
      #strategy: WeightedLeastRequest
      #strategy: Random
      #strategy: RoundRobin

      #strategy: RequestHash
      # requestHashPolicies:
      # - headerHashOptions:
      #     headerName: X-Some-Header
      #   terminal: true
      # - headerHashOptions:
      #     headerName: User-Agent

