apiVersion: v1
kind: Namespace
metadata:
  name: projectcontour-roots
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yages
  name: yages
  namespace: projectcontour-roots

spec:
  replicas: 1
  selector:
    matchLabels:
      app: yages
  template:
    metadata:
      labels:
        app: yages
    spec:
      containers:
        - name: yages
          image: quay.io/mhausenblas/yages:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              protocol: TCP
              name: grpc        


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yages
  name: yages
  namespace: projectcontour-roots
  annotations:
    projectcontour.io/upstream-protocol.h2c: "9000,grpc"    
spec:
  ports:
  - port: 9000
    protocol: TCP
    #targetPort: grpc
    targetPort: 9000
  selector:
    app: yages
  sessionAffinity: None
  type: ClusterIP