apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: projectcontour-roots
spec:
  virtualhost:
    fqdn: local.projectcontour.io
  includes:
    - name: blue
    #- name: green
      namespace: projectcontour-deploy
      conditions:
        - prefix: /deploy

    - name: canary
      namespace: projectcontour-deploy
      conditions:
        - prefix: /deploy/canary

  routes:
    - services:
        - name: rootapp
          port: 80
      conditions:
        - prefix: /
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: blue
  namespace: projectcontour-deploy
spec:
  routes:
    - services:
        - name: blue
          port: 80
          
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: green
  namespace: projectcontour-deploy
spec:
  routes:
    - services:
        - name: green
          port: 80

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: canary
  namespace: projectcontour-deploy
spec:
  routes:
    - services:
        - name: blue
          port: 80
          weight: 100

        - name: green
          port: 80
          weight: 0          
